# Generated by Django 5.2.3 on 2025-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('material', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('num_pieces', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
