# Generated by Django 5.2.3 on 2025-07-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteorder',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quoteorder',
            name='density',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quoteorder',
            name='print_quality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='quoteorder',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'PENDING')], default='PAID', max_length=10),
        ),
    ]
