# Generated by Django 5.2.3 on 2025-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_quoteorder_color_quoteorder_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteorder',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
