# Generated by Django 5.2.3 on 2025-07-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0004_contactus_faq_newsletterlist_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='project_title',
        ),
    ]
