# Generated by Django 5.2.3 on 2025-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0006_quoteorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
